config/routes.rb
Rails.application.routes.draw do
  resources :motels do
    # resource :location, only: [:create, :update]
    member do
      get :point
    end
  end

  resources :countries
  resources :towns
  resources :services
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"
  # get "hostels", to: "hostels#index"

  # Defines the root path route ("/")
  root "motels#index"
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image
  has_and_belongs_to_many :motels

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def new
    @service = Service.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  def create
    @service = Service.new(resource_params)
    # @service.image.attach(params[:image])

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Dot was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end

  end

  def show
    @service = Service.find(params[:id])
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    @service.image.attach(params[:image]) if params[:image]


    respond_to do |format|
      if @service.update(resource_params)
        format.html { redirect_to @service, notice: 'Motel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    respond_to do |format|
      format.html { redirect_to motels_url }
      format.json { head :no_content }
    end
  end

  private

  def resource_params
    permited_fields = [ :title, :description, :image ]
    params.require(:service).permit(permited_fields)
  end
end

app/views/services/_form.html.erb
<%= form_with(model: @service, local: true, html: { multipart: true }) do |form| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% @service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <% if @service.image.attached? %>
    <p>Текущее изображение:</p>
    <%= image_tag @service.image, style: "max-width: 200px;" %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<%= render partial: "form" %>

app/views/services/index.html.erb
<div>
  <h1>Services</h1>
  <%# if current_user.admin?  %>
  <button type="button" class="btn btn-outline-primary">
    <%= link_to I18n.t("activerecord.motel.create_new_motel"), new_service_path %>
  </button>
  <%# end %>
  <table class="table  table-striped">
    <thead>
    <tr>
      <th scope="col"><%= I18n.t("activerecord.service.attributes.name") %></th>
      <th scope="col"><%= I18n.t("activerecord.service.attributes.description") %></th>
    </tr>
    </thead>
    <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><a href="<%= service_path(service) %>">
          <h5> <%= service.title %></h5>
        </a></td>
        <td><%= service.description %></td>
        <td>
          <% if service.image.attached? %>
              <%= image_tag service.image, style: "max-width: 400px;" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/services/new.html.erb
<h1><%= I18n.t("activerecord.service.create_new_service") %></h1>
<%= render partial: "form" %>

app/views/services/show.html.erb
<!--<div>-->
<!--  <div>-->
<!--    <div>-->
<!--      <h1><%#= @service.name %></h1>-->
<!--      <p><%#= @service.description %></p>-->
      <%#= link_to "#{@service.town.name }", town_path(@service.town) %>
<!--      <p><%#= %></p>-->
      <%# @service.images.each do |img| %>
        <%#= image_tag rails_storage_proxy_path(img), size: "512x320" %>
      <%# end %>
<!--         <a href="#" id="showMap">Показать карту</a>-->
<!--      <div id="YMapsID" style="width:500px;height:500px;display:none"></div>-->
<!--      <div id="yandex-map"  data-motel='<%#=@service.slice(:id, :name, :latitude, :longitude)%>' style="width: 50%; height: 400px">-->

<!--      </div>-->

<!--      <script src="https://api-maps.yandex.ru/2.1/?apikey='334c8aeb-9225-4daa-864f-2ef6abce925e'&lang=ru_RU" type="text/javascript"></script>-->


          <%#= link_to 'View all towns', motels_path %>
          <%#= link_to 'Edit', edit_motel_path(@service)%>
<!--          <%= link_to "Destroy", motel_path(@service), data: {    turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %>-->

<!--      </div>-->

<!--  </div>-->
<!--</div>-->

<p>
  <strong>Название:</strong>
  <%= @service.title %>
</p>

<p>
  <strong>Описание:</strong>
  <%= @service.description %>
</p>

<% if @service.image.attached? %>
  <p>
    <strong>Изображение:</strong><br>
    <%= image_tag @service.image, style: "max-width: 400px;" %>
  </p>
<% end %>

<%= link_to 'Редактировать', edit_service_path(@service) %> |
<%= link_to 'Назад', services_path %>