config/routes.rb
Rails.application.routes.draw do
  resources :motels do
    # resource :location, only: [:create, :update]
    member do
      get :point
    end
  end

  resources :countries
  resources :towns
  resources :services
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"
  # get "hostels", to: "hostels#index"

  # Defines the root path route ("/")
  root "motels#index"
end

app/models/motel.rb
class Motel < ApplicationRecord
  geocoded_by :location   # location is the address field
  # after_validation :geocode, if: :will_save_change_to_location?

  validates :latitude, presence: true
  validates :longitude, presence: true

  belongs_to :town
  has_many_attached :images
  has_and_belongs_to_many :services

  def geo_position
    self.latitude & self.longitude ? true : false
  end
end

app/controllers/motels_controller.rb
class MotelsController < ApplicationController
  def index
    @motels = Motel.all
  end

  def new
    @motel = Motel.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @motel }
    end
  end

  def create
    @motel = Motel.new(resource_params)
    @motel.images.attach(params[:images])



    respond_to do |format|
      if @motel.save
        format.html { redirect_to @motel, notice: 'Dot was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @motel.errors, status: :unprocessable_entity }
      end
    end

  end

  def show
    @motel = Motel.find(params[:id])
  end

  def edit
    @motel = Motel.find(params[:id])
    # service = SaveGeoPositionService.new(
    #   # locatable: locatable,
    #   latitude: params[:latitude],
    #   longitude: params[:longitude]
    # )
  end

  def update
    @motel = Motel.find(params[:id])
    @motel.images.attach(params[:images])


    respond_to do |format|
      if @motel.update(resource_params)
        format.html { redirect_to @motel, notice: 'Motel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @motel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @motel = Motel.find(params[:id])
    @motel.destroy
    respond_to do |format|
      format.html { redirect_to motels_url }
      format.json { head :no_content }
    end
  end

  def point
    motel = Motel.find(params[:id].to_i)

    render json: motel.slice(:id, :name, :latitude, :longitude)
  end

  private

  def resource_params
    permited_fields = [ :name, :description, :town_id, :location, :latitude, :longitude, images: [], service_ids: [] ]
    params.require(:motel).permit(permited_fields)
  end
end

app/views/motels/_form.html.erb
<%= form_with model: @motel do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :town_id %><br>
    <%= form.collection_select :town_id, Town.order(:name), :id, :name %>
  </div>
  <h3>Services:</h3>
  <%= form.collection_check_boxes :service_ids, Service.all, :id, :title do |service| %>
    <div>
      <%= service.check_box %>
      <% if service.object.image.attached? %>
        <%= image_tag service.object.image.variant(resize_to_limit: [50, 50]) %>
      <% end %>
      <%= service.label %>
    </div>
  <% end %>
  <div>
    <%= form.label :images %><br>
    <%= form.file_field :images, multiple: true %>
    <% if @motel.images.attached? %>
      <% @motel.images.each do |image| %>
        <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
        <%= image_tag rails_storage_proxy_path(image) %>
        <%= link_to 'Delete image', purge_attachment_path(image),
                    data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>

  </div>

  <!--  <div class="box_image">-->
  <!--    <div class="box_content">-->
  <%#= image_tag image %>
  <%#= check_box_tag "deleted_img_ids[]", image.id %>
  <!--    </div>-->
  <!--  </div>-->

  <div id="map" data-model="motel" style="width: 50%; height: 400px"></div>

  <!--  <script type="module">-->
  <!--      import { lo } from 'special_feature';-->

  <!--      initSpecialFeature();-->
  <!--  </script>-->

  <!--  <script src="https://api-maps.yandex.ru/2.1/?apikey=334c8aeb-9225-4daa-864f-2ef6abce925e&load=Map&lang=ru_RU" type="text/javascript"></script>-->

  <!--  <script>-->
  <!--      ymaps.ready(function () {-->
  <!--          var myMap = new ymaps.Map('map', {-->
  <!--              center: [55.76, 37.64], // Москва, например-->
  <!--              zoom: 10-->
  <!--          });-->
  <!--      });-->
  <!--  </script>-->
  <div>
    <%= form.label :latitude %><br>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude %><br>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/motels/index.html.erb
<div>
  <h1>Motels</h1>
  <%# if current_user.admin?  %>
  <button type="button" class="btn btn-outline-primary">
    <%= link_to I18n.t("activerecord.motel.create_new_motel"), new_motel_path %>
  </button>
  <%# end %>
  <table class="table  table-striped">
    <thead>
    <tr>
      <th scope="col"><%= I18n.t("activerecord.motel.attributes.name") %></th>
      <th scope="col"><%= I18n.t("activerecord.motel.attributes.description") %></th>
    </tr>
    </thead>
    <tbody>
    <% @motels.each do |motel| %>
      <tr>
        <td><a href="<%= motel_path(motel) %>">
          <h5> <%= motel.name %></h5>
        </a></td>
        <td><%= motel.description %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/motels/new.html.erb
<h1><%= I18n.t("activerecord.motel.create_new_motel") %></h1>
<%= render partial: "form" %>

app/views/motels/show.html.erb
<div>
  <div>
    <div>
      <h1><%= @motel.name %></h1>
      <p><%= @motel.description %></p>
      <%= link_to "#{@motel.town.name }", town_path(@motel.town) %>
      <p><%= %></p>
      <% @motel.images.each do |img| %>
        <%= image_tag rails_storage_proxy_path(img), size: "512x320" %>
      <% end %>
      <div>
        <% @motel.services.each  do |service| %>
            <div>
              <%= service.title %>
              <% if service.image.attached? %>
                <%= image_tag service.image.variant(resize_to_limit: [50, 50]) %>
              <% end %>
            </div>
        <% end %>
      </div>

      <div id="yandex-map"  data-motel='<%=@motel.slice(:id, :name, :latitude, :longitude)%>' style="width: 50%; height: 400px"></div>
      <script src="https://api-maps.yandex.ru/2.1/?apikey='334c8aeb-9225-4daa-864f-2ef6abce925e'&lang=ru_RU" type="text/javascript"></script>


          <%= link_to 'View all towns', motels_path %>
          <%= link_to 'Edit', edit_motel_path(@motel)%>
          <%= link_to "Destroy", motel_path(@motel), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
          } %>

      </div>

  </div>
</div>