config/routes.rb
Rails.application.routes.draw do
  resources :motels do
    # resource :location, only: [:create, :update]
    member do
      get :point
    end
  end

  resources :countries
  resources :towns
  resources :services
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"
  # get "hostels", to: "hostels#index"

  # Defines the root path route ("/")
  root "motels#index"
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :towns, dependent: :destroy

  validates :title, presence: true
  # has_and_belongs_to_many :users
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  # load_and_authorize_resource

  def index
    @countries = Country.all
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(resource_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Dot was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end


  end

  def show
    @country = Country.find(params[:id])
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])
    respond_to do |format|
      if @country.update(resource_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    respond_to do |format|
      format.html { redirect_to Countries_url }
      format.json { head :no_content }
    end
  end

  private

  def resource_params
    permited_fields = [ :title, :description ]
    params.require(:country).permit(permited_fields)
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_with model: @country do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/index.html.erb
<div>
  <h1>Countries</h1>
  <%# if current_user.admin?  %>
  <button type="button" class="btn btn-outline-primary">
    <%= link_to I18n.t("activerecord.country.create_new_country"), new_country_path %>
  </button>
  <%# end %>
  <table class="table  table-striped">
    <thead>
    <tr>
      <th scope="col"><%= I18n.t("activerecord.country.attributes.title") %></th>
      <th scope="col"><%= I18n.t("activerecord.country.attributes.description") %></th>
    </tr>
    </thead>
    <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><a href="<%= country_path(country) %>">
          <h5> <%= country.title %></h5>
        </a></td>
        <td><%= country.description %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/countries/new.html.erb
<h1><%= I18n.t("activerecord.country.create_new_country") %></h1>
<%= render partial: "form" %>

app/views/countries/show.html.erb
<div>
  <div>
    <div>
      <h1><%= @country.title %></h1>
      <p><%= @country.description %></p>
    </div>
  </div>
  <div>
    <%= link_to 'View all countries', countries_path %>
    <%= link_to 'Edit', edit_country_path(@country)%>
    <%= link_to "Destroy", country_path(@country), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %>
  </div>
</div>