config/routes.rb
Rails.application.routes.draw do
  resources :motels do
    # resource :location, only: [:create, :update]
    member do
      get :point
    end
  end

  resources :countries
  resources :towns
  resources :services
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"
  # get "hostels", to: "hostels#index"

  # Defines the root path route ("/")
  root "motels#index"
end

app/models/town.rb
class Town < ApplicationRecord
  belongs_to :country
  has_many :motels
  validates :name, presence: true
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  # load_and_authorize_resource

  def index
    @towns = Town.all
  end

  def new
    @town = Town.new
  end

  def create
    @town = Town.new(resource_params)

    respond_to do |format|
      if @town.save
        format.html { redirect_to @town, notice: 'Dot was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end


  end

  def show
    @town = Town.find(params[:id])
  end

  def edit
    @town = Town.find(params[:id])
  end

  def update
    @town = Town.find(params[:id])
    respond_to do |format|
      if @town.update(resource_params)
        format.html { redirect_to @town, notice: 'Town was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @town = Town.find(params[:id])
    @town.destroy
    respond_to do |format|
      format.html { redirect_to towns_url }
      format.json { head :no_content }
    end
  end

  private

  def resource_params
    permited_fields = [ :name, :description, :country_id, :location, :latitude, :longitude ]
    params.require(:town).permit(permited_fields)
  end
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/towns/_form.html.erb
<%= form_with model: @town do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :country_id %><br>
    <%= form.collection_select :country_id, Country.order(:title), :id, :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  <div id="map"  data-model="town"  style="width: 50%; height: 400px"></div>

  <div>
    <%= form.label :latitude %><br>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude %><br>
    <%= form.text_field :longitude %>
  </div>
<% end %>

app/views/towns/index.html.erb
<div>
  <h1>Towns</h1>
  <%# if current_user.admin?  %>
  <button type="button" class="btn btn-outline-primary">
    <%= link_to I18n.t("activerecord.town.create_new_town"), new_town_path %>
  </button>
  <%# end %>
  <table class="table  table-striped">
    <thead>
    <tr>
      <th scope="col"><%= I18n.t("activerecord.town.attributes.name") %></th>
      <th scope="col"><%= I18n.t("activerecord.town.attributes.description") %></th>
    </tr>
    </thead>
    <tbody>
    <% @towns.each do |town| %>
      <tr>
        <td><a href="<%= town_path(town) %>">
          <h5> <%= town.name %></h5>
        </a></td>
        <td><%= town.description %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/towns/new.html.erb
<h1><%= I18n.t("activerecord.town.create_new_town") %></h1>
<%= render partial: "form" %>

app/views/towns/show.html.erb
<div>
  <div>
    <div>
      <h1><%= @town.name %></h1>
      <p><%= @town.description %></p>
      <% @town.motels.each do |m| %>
        <p><%= m.name %></p>
      <% end %>
      <div id="yandex-map"  data-motel='<%=@town.slice(:id, :name, :latitude, :longitude)%>' style="width: 50%; height: 400px">

      </div>

      <script src="https://api-maps.yandex.ru/2.1/?apikey='334c8aeb-9225-4daa-864f-2ef6abce925e'&lang=ru_RU" type="text/javascript"></script>
    </div>
  </div>
  <div>
    <%= link_to 'View all towns', towns_path %>
    <%= link_to 'Edit', edit_town_path(@town) %>
    <%= link_to "Destroy", town_path(@town), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </div>
</div>